//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedViewEntities : DbContext
    {
        public MedViewEntities()
            : base("name=MedViewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<Мед_карта> Мед_карта { get; set; }
        public virtual DbSet<Мед_комиссия> Мед_комиссия { get; set; }
        public virtual DbSet<Осмотр> Осмотр { get; set; }
        public virtual DbSet<Перечень_кабинетов> Перечень_кабинетов { get; set; }
        public virtual DbSet<Поликлиника> Поликлиника { get; set; }
        public virtual DbSet<Предприятие> Предприятие { get; set; }
        public virtual DbSet<Результат> Результат { get; set; }
        public virtual DbSet<Сотрудник_предприятия> Сотрудник_предприятия { get; set; }
        public virtual DbSet<Сотрудники_поликлиники> Сотрудники_поликлиники { get; set; }
        public virtual DbSet<Трудовой_договор> Трудовой_договор { get; set; }
        public virtual DbSet<Уведомление> Уведомление { get; set; }
    }
}
