//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Предприятие
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Предприятие()
        {
            this.Сотрудник_предприятия = new HashSet<Сотрудник_предприятия>();
        }
    
        public int Код_предприятия { get; set; }
        public string Наименование { get; set; }
        public string Краткое_наименование { get; set; }
        public string Юр_адрес { get; set; }
        public int Код_поликлиники { get; set; }
    
        public virtual Поликлиника Поликлиника { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сотрудник_предприятия> Сотрудник_предприятия { get; set; }
    }
}
