//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Результат
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Результат()
        {
            this.Осмотр = new HashSet<Осмотр>();
        }
    
        public int Код_результата { get; set; }
        public string Наименование { get; set; }
        public string Допуск { get; set; }
        public Nullable<int> Код_врача { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Осмотр> Осмотр { get; set; }
        public virtual Сотрудники_поликлиники Сотрудники_поликлиники { get; set; }
    }
}
