//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник_предприятия
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудник_предприятия()
        {
            this.Уведомление = new HashSet<Уведомление>();
        }
    
        public int Код_сотрудника { get; set; }
        public int Табельный_номер { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public string Домашний_адрес { get; set; }
        public int Код_предприятия { get; set; }
        public int Код_мед_карты { get; set; }
        public int Код_трудового_договора { get; set; }


        public string ФИО { get {
                return Фамилия + " " + Имя + " " + Отчество;
            } set {

            } }


        public virtual Мед_карта Мед_карта { get; set; }
        public virtual Предприятие Предприятие { get; set; }
        public virtual Трудовой_договор Трудовой_договор { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Уведомление> Уведомление { get; set; }
    }
}
