//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники_поликлиники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудники_поликлиники()
        {
            this.Результат = new HashSet<Результат>();
            this.Уведомление = new HashSet<Уведомление>();
        }
    
        public int Код_сотрудника_поликлиники { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public int Код_должности { get; set; }
        public int Код_поликлиники { get; set; }


        public string ФИО
        {
            get
            {
                return Фамилия + " " + Имя + " " + Отчество;
            }
            set
            {

            }
        }

        public virtual Должность Должность { get; set; }
        public virtual Поликлиника Поликлиника { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Результат> Результат { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Уведомление> Уведомление { get; set; }
    }
}
