//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Трудовой_договор
    {
        public int Код_трудового_договора { get; set; }
        public System.DateTime Дата_начала_работы { get; set; }
        public Nullable<System.DateTime> Дата_окончания_работы { get; set; }
        public decimal Ставка { get; set; }
        public int Код_должности { get; set; }
    
        public virtual Должность Должность { get; set; }
        public virtual Сотрудник_предприятия Сотрудник_предприятия { get; set; }
    }
}
